### ISSUE TITLE
Webcompat Blipz Experiment icon is wrongly displayed on "non-blipz" websites

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/webcompat-blipz-experiment#100]
**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox 61.0b13

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed though "about:debugging".
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context".
- Have the browser console open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.mozilla.com or another website which is not in the [blipz list ](https://docs.google.com/document/d/1q1e9n9UJ4hGWEjWDGlHgbPu-e1G_dhjUh1jfkIed3uc/edit).
3. Observe the address bar.

**[Expected result]:**
- The "Webcompat Blipz Experiment" icon is not displayed.

**[Actual result]:**
- The "Webcompat Blipz Experiment" icon is displayed.

**[Notes]:**
- The popup can be also accessed when clicking on the "Webcompat Blipz Experiment" icon.
- This issue is also reproducible with other variations ("no-context" and "little-context").
- Attached a screen recording of the issue:
![promt_available_mozilla](https://user-images.githubusercontent.com/20083658/41419234-367cf56c-6ffa-11e8-940f-3f2e67cb03b2.gif)

**Comment by wisniewskit** [comment]
@SoftVision-EmilPasca, this may actually be the intended behavior. After the first time the icon is shown to the user (automatically or using the testing key), it should be available from that point on all non-private tabs, so that the user may report issues on any site (not just the ones the study is expressly interested in).

And while in testing mode, the add-on will remember whether it has shown the prompt unless you fully remove and reinstall it (not just reload it), or you set the variation preference to an empty string (or other unexpected value).

Does this explain why you saw the icon in this case?

**Comment by SoftVision-EmilPasca** [comment]
@wisniewskit Thanks for the explanation, this makes sense.
