### ISSUE TITLE
After resetting the "extensions.webcompat-blipz-experiment.variation" pref its value doesn't automatically change to any of the other variations

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/webcompat-blipz-experiment#121]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the webcompat-blipz-experiment@shield.mozilla.org-1.0.0 installed.
- Have the "extensions.webcompat-blipz-experiment.variation" created in "about:config" with the value "more-context".
- Have the Browser Console open.

**[Steps to reproduce]:**
1. Navigate to "google.com" and press ALT+SHIFT+P to call the popup.
2. Visit about:config and reset the value of `extensions.webcompat-blipz-experiment.variation`string.
3. Observe the pref value.
4. Observe the Browser Console.

**[Expected result]:**
3. The value immediately changes to one of "no-context", "little-context" or "more-context".
4. "Resetting add-on state" message is displayed.

**[Actual result]:**
3. The value remains unchanged.
4. The "Resetting add-on state" message is not displayed.

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- Attached is a screen recording of the issue:

![issue](https://user-images.githubusercontent.com/40061643/41984785-32e6b2b8-7a3a-11e8-9588-4c5339523ee8.gif)

**Comment by miketaylr** [comment]
@wisniewskit can you take a look please?

**Comment by wisniewskit** [comment]
@Softvision-RemusDranca, right-clicking and resetting the value is actually the way to disable testing-mode. That is, the existence of the preference indicates to the add-on that we're in testing mode; if the pref is unset it means "not in testing mode".

Whereas changing that pref to an empty string (or another unexpected value) is meant to simply reset the addon's state, as a shortcut so that testers don't have to uninstall and reinstall it to clear its state. For instance, changing "no-context" to "" will result in it changing right back to "no-context", and the add-on will clear its state.
