### ISSUE TITLE
Implement calls to Shield telemetry

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-blipz-experiment#2]

**Comment by miketaylr** [comment]
Here's my guess based on looking at invision:

| payload data name  | possible payload data values |
| ------------- | ------------- |
| `satisfiedSitePrompt` |  `yes` |
|  |   `no`|
|| `clickedWhySeeingThis`|
|| `clickedDontShowAgain`|
| `shareFeedBack` |  `userCancelled` |
|  |   `userSubmitted`|
| `thankYouPrompt` |  `clickedLearnMore` |

What am I missing?

**Comment by tdsmith** [comment]
Are we firing one payload per interaction sequence, or more incrementally? How do we handle getting multiple responses from e.g. `satisfiedSitePrompt`? If users can dismiss the dialog by clicking away from it, we should capture that somehow.

We should capture voluntary reports and their outcomes somewhere (and distinguish them from random prompts).

**Comment by miketaylr** [comment]
> We should capture voluntary reports and their outcomes somewhere (and distinguish them from random prompts).

Good point. We can manage this via a label on the reported issue. I'll file a bug.

**Comment by miketaylr** [comment]
Filed https://github.com/mozilla/webcompat-blipz-experiment/issues/62.

**Comment by tdsmith** [comment]
>> We should capture voluntary reports and their outcomes somewhere (and distinguish them from random prompts).
>
> Good point. We can manage this via a label on the reported issue. I'll file a bug.

To assess the effects of the different branches (whether context leads to voluntary reporting) we need to have a count in the SHIELD telemetry as well.

**Comment by miketaylr** [comment]
Yes, we need to capture if they self-prompted in Telemetry as well. Good catch.

**Comment by tdsmith** [comment]
This looks good, though if a single SHIELD ping describes a single complete interaction I'm nervous about when we'll know it's time to send a ping if we might be waiting to detect a `thankYouPrompt: clickedLearnMore` condition.

**Comment by wisniewskit** [comment]
@miketaylr, a few questions:
- what precisely is `userDismissed` supposed to track? Simply if the popup was hidden, but not by the user clicking on any of the other buttons or links we provide?
- should we also show this information on the "what will be sent" slide (or at least note that we'll also be sending some telemetry)?
-  if the user has opted out of Shield studies should we deactivate the entire addon? (I will of course not be sending this telemetry if they have specifically opted out of telemetry).

And just to be clear, while we can apparently call Shield's `sendTelemetry` anytime (based on the code), we have to group the data into payloads/ping ourselves, if that's what we want to do. If so, then based on the data we want I will have to wait for one of these conditions before I can be sure the user is done:
- a "thank you" popup is hidden (including if they click the "learn more" link)
- they click "yes" on the first slide or "cancel" on the feedback slides.
- they navigate the tab away to a new URL instead of the above (effectively a "cancel").
- similarly, they close the tab without completing the steps.

That is, if they leave the tab in the background then I'll have to wait (or we'll have to simply assume that if they didn't answer in X seconds, that they effectively canceled, and we should reset the feedback process). And if the tab crashes or the browser is quit, we'll likely get no telemetry at all (which doesn't seem like an issue to me).

Then again, since ping events also have timestamps, it's probably easiest to just send pings all with the same "session id" instead, and not have to worry about grouping the data. (That id would just be the timestamp when the popup was opened on its initial page, and would be sent with all pings related to that "session").

**Comment by tdsmith** [comment]
> should we also show this information on the "what will be sent" slide (or at least note that we'll also be sending some telemetry?

My non-authoritative feeling is "no"; this is all category 2 data that we will receive whether a user submits a report or not, so it doesn't make sense for a user to use this information to help them decide whether to submit a report.

More or less atomic pings should be fine. I think I don't care which pings contain which data; throwing all key-value pairs from the payloads into a single bag with a common (client_id, blipz_session_id) should be easy enough on the back end.

**Comment by wisniewskit** [comment]
>If they've opted out of shield, they won't even get the addon

Hmm. I'll ask on #shield, because I'm not sure how that's supposed to work. I see their sample addon code using `browser.shield.getDataPermissions` and `browser.shield.setup` to determine whether the addon is supposed to do anything, and it otherwise it just does nothing but passively sit there.

**Comment by wisniewskit** [comment]
@miketaylr, why have both `thankYouPrompt`=`clickedLearnMore` and `clickedLearnMore`=`yes`?

**Comment by miketaylr** [comment]
> @miketaylr, why have both thankYouPrompt=clickedLearnMore and clickedLearnMore=yes?

I'm not sure that's... a meaningful distinction. Might be leftover from first pass. Let's remove `thankYouPrompt=clickedLearnMore`.
